server:
  port: 8081

logging:
  level:
    org.springframework.security.oauth2: trace

spring:
  security:
    oauth2:
      client:
        registration:
          bff_server:
            client-id: "client"
            client-secret: "{noop}secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "http://anotherlocalhost.com:8081/oauth2/authorization/bff_server"
            scope:
              - "openid"
            client-name: "client"
            provider: "authorization_server"
        provider:
          authorization_server:
            authorization-uri: "http://localhost:9000/oauth2/authorize"
            token-uri: "http://localhost:9000/oauth2/token"
            jwk-set-uri: "http://localhost:9000/oauth2/jwks"
            issuer-uri: "http://localhost:9000"
            user-info-uri: "http://localhost:9000/userinfo"
            user-info-authentication-method: "header"
            user-name-attribute: "sub"