server:
  port: 8081

logging:
  level:
    org.springframework.security.oauth2.client: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          bff:
            client-id: client
            client-secret: secret
            authorization-grant-type: client_credentials
#            scope:
#              - api.read
            client-name: client
            provider: spring
        provider:
          spring:
            token-uri: http://localhost:9000/oauth2/token